services:
  file-watcher:
    image: ${PROJECT_NAME}:${PROJECT_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
         PROJECT_NAME: ${PROJECT_NAME}
         USER_HOME: ${USER_HOME}
#    command: ${USER_HOME}/file_watcher.py
    volumes:
      - ./data:${USER_HOME}/data:rw
    container_name: "${PROJECT_NAME}" 
    tty: true
    stdin_open: true

